ignore:
  - "app/features/combo/**/*"
  - "app/features/combo-state/**/*"
  - "app/features/edit-customer-profile/**/*"
  - "app/features/my-combos/**/*"
  - "app/features/notification/**/*"
  - "app/features/product/**/*"
  - "app/features/product-analytics/**/*"
  - "app/features/profile/**/*"
  - "app/features/sales/**/*"
  - "app/features/seller-dashboard-settings/**/*"
  - "app/features/seller-details/**/*"
  - "app/features/sign-out/**/*"
  - "app/features/splash/**/*"
  - "app/features/wishlist/**/*"
