ignore:
  - "app/features/combo/**/*"
  - "app/features/combo-state/**/*"
  - "app/features/edit-customer-profile/**/*"
  - "app/features/my-combos/**/*"
  - "app/features/notification/**/*"
  - "app/features/product/**/*"
  - "app/features/product-analytics/**/*"
  - "app/features/profile/**/*"
  - "app/features/sales/**/*"
  - "app/features/seller-dashboard-settings/**/*"
  - "app/features/seller-details/**/*"
  - "app/features/sign-out/**/*"
  - "app/features/splash/**/*"
  - "app/features/wishlist/**/*"
  - "app/features/forgot-password/**/*"
  - "app/shared/components/product-card/**/*"
  - "api/analytics/**/*"
  - "api/combos/**/*"
  - "api/cust_analytics/**/*"
  - "api/custom_profile/**/*"
  - "api/inventory/**/*"

