version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    depends_on:
      - db
  db:
    image: postgres:14.7
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: