version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
  db:
    image: postgres:14.7
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  celery:
    build: ./api
    command: celery -A api.celery worker --loglevel=info
    volumes:
      - ./api:/api
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
