version: "3"
services:
  api:
    build:
      context: ./api
    env_file:
      - api/api/.env
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
  db:
    image: postgres:14.7
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h $${POSTGRES_HOST} -d $${POSTGRES_DB} -U $${POSTGRES_USER}",
        ]
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_HOST: "0.0.0.0"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
