# Generated by Django 4.2.1 on 2023-05-23 06:14

import consumer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(default='consumer', max_length=8)),
                ('wishlist', models.JSONField(default=consumer.models.get_default_data)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
