# Generated by Django 4.2.1 on 2023-06-05 00:57

import consumer.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(
                    default='consumer', editable=False, max_length=8)),
                ('wishlist', models.JSONField(
                    default=consumer.models.get_default_data)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
