# Generated by Django 4.2.1 on 2023-05-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('SELLER', 'Male'), ('USER', 'Female')], max_length=6)),
            ],
        ),
    ]
