# Generated by Django 4.2.1 on 2023-05-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('SELLER', 'seller'), ('USER', 'user')], max_length=6),
        ),
    ]
