# Generated by Django 4.2.1 on 2023-05-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=14, unique=True)),
                ('business_name', models.CharField(max_length=30)),
                ('business_type', models.CharField(max_length=100)),
                ('catalogue_size', models.IntegerField(default=0)),
                ('busines_category', models.CharField(choices=[('MICRO', 'micro'), ('SMALL', 'small'), ('MEDIUM', 'medium')], max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('SUSPENDED', 'suspended')], max_length=9)),
                ('website', models.URLField(unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='owner')),
            ],
        ),
    ]
