# Generated by Django 4.2.1 on 2023-06-08 01:31


from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(default='seller', editable=False, max_length=6)),
                ('reg_no', models.CharField(max_length=14, unique=True)),
                ('business_name', models.CharField(max_length=30)),
                ('business_type', models.CharField(max_length=100)),
                ('catalogue_size', models.IntegerField(default=0)),
                ('business_category', models.CharField(choices=[('MICRO', 'micro'), ('SMALL', 'small'), ('MEDIUM', 'medium')], max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('SUSPENDED', 'suspended')], max_length=9)),
                ('is_verified', models.BooleanField(default=False)),
                ('website', models.URLField(unique=True)),
                ('feed_url', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
