name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to app directory
        run: cd app

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build --prod

      - name: Run tests
        run: yarn test
