name: Build and Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Create .env file
        # env:
        #   # DjangoSecretKey: ${{ secrets.API_ENV}}
        #   # DjangoSecretKey1: ${{ secrets.API_ENV_PROD}}
        #   # Cognito: "${{secrets.APP_ENV_PROD_TS}}"
        #   # CognitoClientPool2: "${{secrets.APP_ENV_TS}}"
        run: |
          echo "${{ secrets.API_ENV}}" > ./api/api/.env
          echo "${{ secrets.API_ENV_PROD}}" > ./api/api/env.prod.ts
          echo "${{secrets.APP_ENV_TS}}" > ./app/src/environments/env.ts
          echo "${{secrets.APP_ENV_PROD_TS}}" > ./app/src/environments/env.prod.ts

      - name: Install dependencies
        working-directory: ./app
        run: yarn install

      - name: Build project
        working-directory: ./app
        run: yarn build

    # build: artifact for deployment
    # - name: Archive Build Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: dist-artifact
    #     path: dist
    #     retention-days: 1
