name: Build

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --legacy-peer-deps

      #   - name: Run tests
      #     run: yarn test

      - name: Build app
        run: yarn build
