name: Build and Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./app
        run: yarn install

      - name: Lint Code
        working-directory: ./app
        run: yarn lint

      # - name: Run Backend Unit Tests
      #   working-directory: ./app
      #   run: yarn api:test

  build:
    needs: lint_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Create .env file
        env:
          DjangoSecretKey: ${{ secrets.API_ENV}}
          DjangoSecretKey1: ${{ secrets.API_ENV_PROD}}
          CognitoUserPool: ${{secrets.APP_ENV_PROD_TS}}
          CognitoClientPool2: ${{secrets.APP_ENV_TS}}
        run: |
          echo "DjangoSecretKey=$DjangoSecretKey" > ./api/api/.env
          echo "CognitoUserPool=$CognitoUserPool" > ./api/api/env.prod.ts
          echo "CognitoClientPool2=$CognitoClientPool2" > ./app/src/environments/env.ts
          echo "DjangoSecretKey1=$DjangoSecretKey1" > ./app/src/environments/env.prod.ts

      - name: Install dependencies
        working-directory: ./app
        run: yarn install

      - name: Build project
        working-directory: ./app
        run: yarn build

    # build: artifact for deployment
    # - name: Archive Build Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: dist-artifact
    #     path: dist
    #     retention-days: 1
