name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Create .env file
        env:
          DjangoSecretKey: ${{ secrets.API_ENV}}
          CognitoUserPool: ${{secrets.API_ENV_PROD_TS}}
          CognitoClientPool2: ${{secrets.API_ENV_TS}}
        run: |
          echo "DjangoSecretKey=$DjangoSecretKey" > ./api/api/.env
          echo "CognitoUserPool=$CognitoUserPool" > ./app/src/environments/env.prod.ts
          echo "CognitoClientPool2=$CognitoClientPool2" > ./app/src/environments/env.ts

      - name: Install dependencies
        working-directory: ./app
        run: yarn install

      - name: Build project
        working-directory: ./app
        run: yarn build

      - name: Run tests
        working-directory: ./app
        run: yarn test
