name: Deploy to Amazon ECS

on:
  push:
    branches:
      - JY/00/deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "${{ secrets.API_ENV_PROD}}" > ./api/api/.env

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: ./api/api/.env
          export-variables: true
        env:
          AWS_REGION: ${{ steps.dotenv.outputs.AWS_PROD_REGION }}
          ECR_REPOSITORY: ${{ steps.dotenv.outputs.ECR_REPOSITORY }}
          ECS_SERVICE: ${{ steps.dotenv.outputs.ECS_SERVICE }}
          ECS_CLUSTER: ${{ steps.dotenv.outputs.ECS_CLUSTER }}
          ECS_TASK_DEFINITION: ${{ steps.dotenv.outputs.ECS_TASK_DEFINITION }}

          CONTAINER_NAME: ${{ steps.dotenv.outputs.CONTAINER_NAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ steps.dotenv.outputs.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ steps.dotenv.outputs.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        working-directory: api

        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
